new const HUMAN_INFECTED_SND[][]={"zombi/z4/all/z4human_death_male.wav", "zombi/z4/all/z4human_death_female.wav"}
new const ZOMBIE_COMEBACK[]={"vox/z4_zombi_comeback.wav"}
//new const SND_NVG[][]={"items/nvg_off.wav", "items/nvg_on.wav"}
new const ZOMBIE_COMING[][]={"vox/z4_zombi_coming_1.wav","vox/z4_zombi_coming_2.wav"}

#if 0
#define ZOMBIE_NVG_R			85
#define ZOMBIE_NVG_G			74
#define ZOMBIE_NVG_B			131
#define ZOMBIE_NVG_A			80

#define ZOMBIE_NVG_NIGHT_R		124
#define ZOMBIE_NVG_NIGHT_G		66
#define ZOMBIE_NVG_NIGHT_B		47
#define ZOMBIE_NVG_NIGHT_A		66
#endif

#if 0
#define ZOMBIE_NVG_NIGHT_R		141
#define ZOMBIE_NVG_NIGHT_G		63
#define ZOMBIE_NVG_NIGHT_B		12
#define ZOMBIE_NVG_NIGHT_A		60
#endif